### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by Jakub-Bielawski** [edgeimpulse/example-esp32-cam#1]
Hello, I'm following the steps from Basic example, after compiling I get following error. Do you have any advice ? 

Basic-Image-Classification:4:10: fatal error: vector: No such file or directory
 #include <vector>
          ^~~~~~~~
compilation terminated.
exit status 1
vector: No such file or directory

**Comment by luisomoreau** [comment]
Can you make sure you have selected one of the ESP board in the board manager please. This error usually appears when trying to compile for the Arduino Uno.
You can try to compile with the AI Thinker board to make sure it works.
If it does not work, can you try removing the ESP boards and install them again

**Comment by luisomoreau** [comment]
Hey @Jakub-Bielawski ,

Yes it is at the moment a known issue, I will probably work on that next week. I'm traveling at the moment for business and don't have a ESP32 Cam with me.
You also can check the forum https://forum.edgeimpulse.com/t/esp32-cam-support/797/116 (pretty long thread though)

Did you try the Basic example or the Advanced example?
The basic one has only a cutout function that basically cutout some pixels of the image whereas the Advance one uses a bilinear interpolation to resize the image. I'm suspecting the issues comes from the image that is passed to the run_inference function doesn't really match with the images the models have been trained with.

Regards,

Louis

**Comment by Jakub-Bielawski** [comment]
I'll check forum for sure. I was trying both examples. I have similar suspicions about pixel values. I'm also trying to make, train, quantize and deploy my own custom simple model (few Conv2D, MaxPool and FullyConected layers). I done everything like tensorflow suggested but i think there is some issue with pixel values. Maybe you can help me, because I'm not sure which type and scale should it be.  During quantification, I'm using 
converter.inference_input_type = tf.int8 # or tf.uint8
converter.inference_output_type = tf.int8 # or tf.uint8
but I don't know how to check range. I'm training my model with grayscale image in range(0., 1.). As tensorflow write on their blog layers are in [-127,127] range but still nothing about input. I'm asking because  maybe you faced this problem :) 

I'll be thankful for any advice :)

Jakub
Re

**Comment by luisomoreau** [comment]
Hello!
Could you try using RGB instead of greyscale also and let me know if you still have you problem?
Regards,

**Comment by Jakub-Bielawski** [comment]
Hi, I've checked RGB on MobileNetv2 0.05 48x48x3, and got still same problem, always same prediction with almost 100% certainty. I'm using Basic classification because Advance does not include ep-eye selection in board model. Should I change anything other than the wifi ssid/password and library name?  I'm not sure about fmt2tgb888 line in void classify(). Thanks for your support :)

**Comment by Jakub-Bielawski** [comment]
Hi Louis, 
I solved the problem, it turned out to be totally my fault, I didn't delete the previous attached libraries, so apparently the correct model was not loaded, which was causing errors, so far I checked Basic example, the predictions are not perfect but it probably results from this what did you say about cutting image and not actual scaling. The final settings for inference are:

MobileNetV2 0.05 48x48x1

If you know something that can help me with my own quantization and inference, please let me know :)  

Thanks for your support :)

**Comment by luisomoreau** [comment]
@Jakub-Bielawski,
Also to add the ESP EYE for the advance sketch example, just add:
```
#define CAMERA_MODEL_ESP_EYE
```
And comment the other boards

I haven't tested but I guess it should work as this board has PSRAM.

Regards,

Louis

**Comment by Jakub-Bielawski** [comment]
I did that and it works, but i had to also add this 

```
#if defined(CAMERA_MODEL_ESP_EYE)
  pinMode(13, INPUT_PULLUP);
  pinMode(14, INPUT_PULLUP);
#endif
```
in Advance-Image-Classification.ino
In advance example I was trying MobileNetV2 0.05 32x32x3, and I think it works pretty well
For future work I'll try larger versions of MobileNetV2 and smaller frame size like capturing 96x96, maybe it will work :) 

Jakub

**Comment by luisomoreau** [comment]
Thanks for this, I'm adding this to the code!
